# Site
name: "Canal Di Fora"
title: "Canal Di Fora"
description: "Ter uma idéia, escrever o roteiro, preparar a câmera, editar e subir para o YouTube."
logo: 'assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: '/webpage'
google_analytics: 'UA-188126338-1'
#disqus: 'demowebsite'
mailchimp-list: 'https://canaldifora.us7.list-manage.com/subscribe/post?u=eb5ba1ecaefa643165a64733f&amp;id=c56856ab79'
include: ["_pages"]
permalink: /post/:title/
email: canaldifora@gmail.com

# Authors
authors:
  diegobarreto:
    name: Diego Barreto
    display_name: Diego Barreto
    avatar: assets/images/avatar.png
    email: canaldifora@gmail.com
    web: https://www.youtube.com/channel/UCTT6LqmWV53OdwIJchQvFGg
    twitter: https://twitter.com/diegobqb
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-6722686573375023"
adsense-data-ad-slot: "6397569963"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
